import pandas as pd
from collections import defaultdict
from pypinyin import lazy_pinyin, Style
import os
import sys

def convert_to_pinyin(province, city):
    p = ''.join(lazy_pinyin(province, style=Style.NORMAL))
    c = ''.join(lazy_pinyin(city, style=Style.NORMAL))
    return f"{c.title()}, {p.title()}"

def process_data_list(data_list):
    processed = set()
    result = []
    
    location_groups = defaultdict(list)
    for item in data_list:
        key = f"{item['province']}{item['city']}"
        location_groups[key].append(item)

    for location, numbers in location_groups.items():
        prefix_groups = defaultdict(list)
        
        for num in numbers:
            phone_str = str(num['phone'])
            if phone_str not in processed:
                prefix = phone_str[:-1]
                prefix_groups[prefix].append(num)

        for prefix, group in prefix_groups.items():
            if len(group) == 10:
                sorted_group = sorted(group, key=lambda x: str(x['phone']))
                if all(str(n['phone'])[-1] == str(i) for i, n in enumerate(sorted_group)):
                    first = sorted_group[0]
                    if all(n['province'] == first['province'] and n['city'] == first['city'] for n in sorted_group):
                        result.append({
                            'phone': int(prefix),
                            'province': first['province'],
                            'city': first['city']
                        })
                        processed.update(str(n['phone']) for n in sorted_group)

    for item in data_list:
        if str(item['phone']) not in processed:
            result.append(item)
    
    return result

def optimize_loop(input_file):
    df = pd.read_csv(input_file)
    current_data = df.to_dict('records')
    
    round_num = 1
    while True:
        initial_count = len(current_data)
        print(f"::notice::Starting Round {round_num} optimization...")
        
        new_data = process_data_list(current_data)
        final_count = len(new_data)
        
        print(f"Round {round_num}: {initial_count} -> {final_count} records")
        
        if final_count == initial_count:
            print(f"::notice::Optimization finished at Round {round_num}. No more merges possible.")
            break
        
        current_data = new_data
        round_num += 1
    
    final_df = pd.DataFrame(current_data)
    final_df.sort_values(by='phone', inplace=True)
    
    optimized_zh = {}
    optimized_en = {}

    for _, row in final_df.iterrows():
        phone = int(row['phone'])
        optimized_zh[phone] = f"{row['province']}{row['city']}"
        optimized_en[phone] = convert_to_pinyin(row['province'], row['city'])
        
    return optimized_zh, optimized_en

def generate_optimized_dart_files(optimized_zh, optimized_en):
    os.makedirs('lib/cn', exist_ok=True)
    with open('lib/cn/phone_location_zh_optimized.dart', 'w', encoding='utf-8') as f:
        f.write('// Generated by GitHub Actions\n')
        f.write('Map<int, String> get86_zh_optimized() {\n  return {\n')
        for phone, location in optimized_zh.items():
            f.write(f'    {phone}: "{location}",\n')
        f.write('  };\n}\n')

    with open('lib/cn/phone_location_en_optimized.dart', 'w', encoding='utf-8') as f:
        f.write('// Generated by GitHub Actions\n')
        f.write('Map<int, String> get86_en_optimized() {\n  return {\n')
        for phone, location in optimized_en.items():
            f.write(f'    {phone}: "{location}",\n')
        f.write('  };\n}\n')

if __name__ == "__main__":
    optimized_zh, optimized_en = optimize_loop('lib/cn/phone_location_processed.csv')
    generate_optimized_dart_files(optimized_zh, optimized_en)
