name: Publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: 'Publish'

    environment: pub.dev

    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get

      - name: Publish to pub.dev
        run: dart pub publish -f