name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: 'Publish to pub.dev'

    environment: pub.dev

    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
      
      # Setup package dependencies
      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run

      # # Publishing...
      # - name: Publish to pub.dev
      #   run: dart pub publish -f
      #   working-directory: ${{ inputs.working-directory }}

