name: Release

on:
  schedule:
    - cron: '0 12 * * *'        # Runs every day at 12:00 PM UTC
  workflow_dispatch:            # Allow manual trigger
  
permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    environment: pub.dev
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install package dependencies
        run: dart pub get

      - name: Run update resources script
        run: ./update_resources.sh
