name: Release

on:
  schedule:
    - cron: '0 12 * * *'        # Runs every day at 12:00 PM UTC
  workflow_dispatch:            # Allow manual trigger

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DLIBPHONENUMBER_TOKEN }}

      - name: Set-up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install package dependencies
        run: dart pub get

      - name: Run update resources script
        run: ./update_resources.sh
